version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: ticket_postgres
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123455
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: ticket_redis
    ports:
      - "6379:6379"